### ISSUE TITLE
digitalpeni.org: some things to be done on the website

### ISSUE THREAD

**Issue by nikzam93** [juncture-digital/juncture#20]
1. background of the website everywhere, e.g. light green (in all cards, etc)
2. insert the logo
<img width="137" alt="post-doc-logo" src="https://github.com/juncture-digital/juncture/assets/98533098/1cb06b43-1f90-4086-9ccc-a61c41e9d4b8"> as a small icon on the cartel/heading of the website's window when open it on browser
3. all the logos to be in the same line on the initial website
4. remove the M from the website's end/footer everywhere
5. Juncture's logo as Powered by Juncture and its logo alongside (footer) everywhere
6. fix some bugs/errors in all poets' cards as some of them does not work and show a blank page when load them, e.g. 
[http://digitalpeni.org/aντιρομαντικές-τάσεις-στην-Αθήνα/αριστομένης-προβελλέγιος] & 
[http://digitalpeni.org/μήτσος-παπανικολάου]
7. the link of OSF does not work on the card "Μεταδιδακτορική Έρευνα": [http://digitalpeni.org/nikzam93/digitalpeni/osf.io/jcrky]. The link to mention is [https://osf.io/jcrky] and shall be mentioned with the reference Open Science Framework
8. Contact/Επικοινωνία: nikzamp@phil.uoa.gr (kindly add my e-mail)
9. How can I add photos e.g. from Wikimedia Commons inside the text? I mean that when we have a reference for cherries, which is the code to link a photo with the reference of a line?

**Comment by rsnyder** [comment]
1. In this version of Juncture you will need to add some custom CSS to each page to modify background colors and such.  The Juncture documentation describes this in the General [Styling page](https://www.juncture-digital.org/styling/general).  Below is a text snippet showing how this would be done.

```css
<style>
    #juncture {
        background-color: #F0FDF0;
    }
</style>
```

The `#F0FDF0` is a hex code for light green. Please feel free to change this as needed to match the particular color of green you had in mind.  There are a number of websites that provide color pickers for generating color hex codes.

**Comment by nikzam93** [comment]
<img width="147" alt="SAMPLE" src="https://github.com/juncture-digital/juncture/assets/98533098/5b344deb-2aee-475c-9998-350d762c3ddb">

2. To add the post-doc's logo instead of the Earth's logo on the cartel / window when open it on our browser.

**Comment by rsnyder** [comment]
4. (and 5.) Page footers can be removed entirely or customized.  The [Juncture .ve-footer documentation page](https://www.juncture-digital.org/components/footer) provides some info on this.

To remove the default footer you can simply add a `.ve-footer` tag to your page without any list items.  For instance,

```html
.ve-footer
```

To add a custom footer, the `.ve-footer` tag is followed by one or more Markdown list elements defining the footer elements.  For instance,

```html
.ve-footer
    - Powered by: [![Juncture Logo](https://juncture-digital.github.io/juncture/static/images/juncture-logo.png)](https://juncture-digital.org)
    - [![CC BY](https://licensebuttons.net/l/by/4.0/88x31.png)](https://creativecommons.org/licenses/by/4.0/)
    - [About](/about)
 ```

**Comment by rsnyder** [comment]
#2 - Ahh, I see.  You're asking about a [favicon](https://en.wikipedia.org/wiki/Favicon).  A favicon is a special image that can be added to a window or tab title.  I will post an update for setting a custom favicon for your site.  If you don't already have a favicon-compatible image there are some websites that can be used to convert a regular image into a favicon.  Here's one that comes up in a Google search - https://favicon.io/.

**Comment by nikzam93** [comment]
> 1. In this version of Juncture you will need to add some custom CSS to each page to modify background colors and such.  The Juncture documentation describes this in the General [Styling page](https://www.juncture-digital.org/styling/general).  Below is a text snippet showing how this would be done.
> 
> ```css
> <style>
>     #juncture {
>         background-color: #F0FDF0;
>     }
> </style>
> ```
> 
> The `#F0FDF0` is a hex code for light green. Please feel free to change this as needed to match the particular color of green you had in mind. There are a number of websites that provide color pickers for generating color hex codes.



Can I insert the above to all pages?

**Comment by nikzam93** [comment]
> 4. (and 5.) Page footers can be removed entirely or customized.  The [Juncture .ve-footer documentation page](https://www.juncture-digital.org/components/footer) provides some info on this.
> 
> To remove the default footer you can simply add a `.ve-footer` tag to your page without any list items. For instance,
> 
> ```
> .ve-footer
> ```
> 
> To add a custom footer, the `.ve-footer` tag is followed by one or more Markdown list elements defining the footer elements. For instance,
> 
> ```
> .ve-footer
>     - Powered by: [![Juncture Logo](https://juncture-digital.github.io/juncture/static/images/juncture-logo.png)](https://juncture-digital.org)
>     - [![CC BY](https://licensebuttons.net/l/by/4.0/88x31.png)](https://creativecommons.org/licenses/by/4.0/)
>     - [About](/about)
> ```

Can I insert the above to all pages?

**Comment by rsnyder** [comment]
Yes, a custom footer can be added to each page.  Unfortunately, in this version of Juncture there is no means for setting this once and having it globally applied to all pages.

**Comment by nikzam93** [comment]
> Yes, a custom footer can be added to each page. Unfortunately, in this version of Juncture there is no means for setting this once and having it globally applied to all pages.

I have now tried to add the .ve footer and the other for the background to each page and seems that only on the initial page are seen, not the rest. Moreover, the icon of license at the ve.footer seems broken when click on it.

**Comment by rsnyder** [comment]
2. If you have a favicon (and by convention these are named `favicon.ico`), upload the file to the root directory of your repository and modify the `index.html` file in the root folder to add a reference to the favicon.  For instance, below is a snippet showing the needed change.  It can go anywhere in the `head` section in the file.  In the snippet below I show it added immediately following the `title` tag.

```html
  <title></title>
  <link href="/favicon.ico" rel="icon"/>
```

Note that it can sometimes take a little while for this change to appear on the live site.

**Comment by nikzam93** [comment]
#3 has been solved

**Comment by nikzam93** [comment]
1.fix some bugs/errors in all poets' cards as some of them does not work and show a blank page when load them, e.g.
[http://digitalpeni.org/aντιρομαντικές-τάσεις-στην-Αθήνα/αριστομένης-προβελλέγιος] &
[http://digitalpeni.org/μήτσος-παπανικολάου]
2.the link of OSF does not work on the card "Μεταδιδακτορική Έρευνα": [http://digitalpeni.org/nikzam93/digitalpeni/osf.io/jcrky]. The link to mention is [https://osf.io/jcrky] and shall be mentioned with the reference Open Science Framework
3.Contact/Επικοινωνία: nikzamp@phil.uoa.gr (kindly add my e-mail)
4.How can I add photos e.g. from Wikimedia Commons inside the text? I mean that when we have a reference for cherries, which is the code to link a photo with the reference of a line?
5. May I insert the green background everywhere (e.g. on that pages with the cards)? I have tried but nothing.
6. May I insert the .ve footer to each page's end? I have tried but nothing. 
7. ve.footer: the website of creative commons license is not working

**Comment by rsnyder** [comment]
3. The [Juncture header documentation page(https://www.juncture-digital.org/components/header) has been updated to show how a contact form link may be added to a page header with custom fields for defining the recipients email address, an email subject, and a title for the form.  For instance, using your home page header as an example,
   
```html
.ve-header "Ψηφιακές Οικολογίες" wc:The_beautiful_white_rose_flower.jpg "Η χρήση του ψηφιακού εργαλείου Juncture στη Νεοελληνική Ποίηση του 19ου-20ού αιώνα" contact-form-title="Contact form for Some Site" contact-subject="Contact form for Some Site" contact=someone@somesite.org
    - [Αρχική](/)
    - [Μεταδιδακτορική Έρευνα](/έρευνα)
    - [Αρκαδισμός](/aρκαδισμός)
    - [Νεοκλασικισμός](/nεοκλασικισμός)
    - [Ρομαντισμός στα Επτάνησα](/pομαντισμός-στα-eπτάνησα)
    - [Ρομαντισμός στην Αθήνα](/pομαντισμός-στην-aθήνα)
    - [Αντι-ρομαντικές τάσεις στην Αθήνα](/aντι-ρομαντικές-τάσεις-στην-Αθήνα)
    - [Παρνασσισμός και Συμβολισμός](/παρνασσισμός-συμβολισμός)
    - [Συμβολισμός και Μετά-συμβολισμός](/Συμβολισμός-Μετα-συμβολισμός)
    - [Μοντερνισμός. Υψηλός Μοντερνισμός και Πρωτοπορία: Υπερρεαλισμός](/μοντερνισμός-υψηλός-μοντερνισμός-πρωτοπορία-υπερρεαλισμός)
    - [Επικοινωνία](/επικοινωνία)
    - [Contact us](contact)
```

The text "contact" in the menu item link must be in English, but the "Contact Us" text for the link label can be expressed in Greek (or any language).  Similarly, the values for the .ve-header attributes (`contact-form-title` and `contact-subject`) can also be defined in any language.

**Comment by nikzam93** [comment]
1.fix some bugs/errors in the below:

[http://digitalpeni.org/aντιρομαντικές-τάσεις-στην-Αθήνα/αριστομένης-προβελλέγιος] &

[http://digitalpeni.org/μήτσος-παπανικολάου]

**Comment by nikzam93** [comment]
How may I link a website with a logo?

**Comment by nikzam93** [comment]
How can I add photos e.g. from Wikimedia Commons inside the text? I mean that when we have a reference for cherries, which is the code to link a photo with the reference of a line?

May I insert the green background everywhere (e.g. on that pages with the cards)? I have tried but nothing.

May I insert the .ve footer to each page's end? I have tried but nothing.

**Comment by nikzam93** [comment]
> Please say more about "How can I add photos e.g. from Wikimedia Commons inside the text? I mean that when we have a reference for cherries, which is the code to link a photo with the reference of a line?"
> 
> The Juncture `.ve-media` tag is intended to be used for adding an image to a Juncture essay. There are many examples of showing the use of the .ve-media tag in the Juncture documentation, including many examples of doing this with Wikimedia Commons images. Are you looking to do something different?

For example, I wish to link a photo of cherries from Wikimedia Commons to a reference for cherries within the Greek text.

**Comment by rsnyder** [comment]
I'm still not sure I understand.  Do you wish to display a photo of cherries in the text, or show a popup (with a picture of cherries) when clicking on or hovering over a text reference?  If you simply want to display a photo of cherries in the essay (and optionally wrap text around it) the .ve-media tag would work for this, using something like the following

```html
.ve-media wc:Cherry_Stella444.jpg static left caption="Κεράσια"
```

In this example, the `caption` attribute is used to replace the default caption (typically in English) with a custom one.

**Comment by nikzam93** [comment]
> I'm still not sure I understand. Do you wish to display a photo of cherries in the text, or show a popup (with a picture of cherries) when clicking on or hovering over a text reference? If you simply want to display a photo of cherries in the essay (and optionally wrap text around it) the .ve-media tag would work for this, using something like the following
> 
> ```
> .ve-media wc:Cherry_Stella444.jpg static left caption="Κεράσια"
> ```
> 
> In this example, the `caption` attribute is used to replace the default caption (typically in English) with a custom one.

we have e.g. a reference of a flower in the Greek text, e.g. radish, rose, etc., create a hyperlink on this word and when click on it to transfer ourselves into its photo alongside

this will be done in some of the world of flora, not all the references, indeed :)

**Comment by nikzam93** [comment]
> show a popup (with a picture of cherries) when clicking on

maybe this...
 "show a popup (with a picture of cherries) when clicking on" 

An example of "hovering" in order to understand it?

**Comment by rsnyder** [comment]
If you just want to link some text in your essay to another page you can just use the regular Markdown linking, for instance

```markdown
[Κεράσια](https://commons.wikimedia.org/wiki/File:Cherry_Stella444.jpg)
```

Juncture entity popovers are described here - https://www.juncture-digital.org/getting-started?id=add-entity-popovers

An entity popover is used to display an info box (with text and an image) when a user hovers over some marked text.  These are used in many Juncture essays to provide supplemental information for terms in essay text.

**Comment by nikzam93** [comment]
<img width="1440" alt="Στιγμιότυπο 2023-05-26, 6 44 03 μμ" src="https://github.com/juncture-digital/juncture/assets/98533098/b7c37cc8-0cb7-474c-9b42-d771446761db">

I am attaching a screenshot to understand it better. I have circled the reference radish in Greek and wish e.g. to link a photo of radish from Wikimedia Commons with the in-text reference, and then alongside to see its photo. My query is where shall I have to insert the code at Github and which is the sample?

**Comment by nikzam93** [comment]
ok
