### ISSUE TITLE
Editor window won't launch correctly

### ISSUE THREAD

**Issue by annhanlon** [juncture-digital/juncture#34]
When opening the Editor today, the editor window won't launch, and it is not possible to enter any content. This is happening for me, as well as for other users. I learned about the issue from a student who was seeking assistance. This is happening for me in both Chrome and Edge. See the screenshot:
![juncture-window](https://github.com/user-attachments/assets/087223da-1c8c-4223-8c28-4f1376d4fe1f)

**Comment by rsnyder** [comment]
Thank you for reporting this.  I'm seeing the same thing,  It appears that an external dependency (CodeMirror) is failing to load.  I will look into this and post an update here after I know more.

**Comment by annhanlon** [comment]
Thank you - checking in to see if there has been any progress? I'll update the class once it's resolved, Thank you!

Ann


Ann Hanlon, M.L.I.S., M.A.
Head, Digital Collections and Initiatives and DH Services
University of Wisconsin-Milwaukee Libraries
pronouns-in-use: she/her/hers
________________________________

**Comment by rsnyder** [comment]
Ann,

I’m working on a fix, or at least an interim solution.  I’m hoping to have something in place in the next day or two.  I’ll post an update when it’s ready.

Also, I’d be interested in hearing more about how this is being used in class if you’d care to share some details when you have a chance.

Ron

**Comment by rsnyder** [comment]
Sure, you can use ***@***.***  RonOn Sep 9, 2024, at 2:57 PM, Ann Hanlon ***@***.***> wrote:﻿
Thanks, Ron. I would love to share the assignment with you - is there a separate email I can use to do that so it doesn't post to the github? Thank you!!



Ann





Ann Hanlon, M.L.I.S., M.A.

Head, Digital Collections and Initiatives and DH Services

University of Wisconsin-Milwaukee Libraries

pronouns-in-use: she/her/hers

________________________________

From: Ron Snyder ***@***.***>

Sent: Monday, September 9, 2024 11:54 AM

To: juncture-digital/juncture ***@***.***>

Cc: Ann M Hanlon ***@***.***>; Author ***@***.***>

Subject: Re: [juncture-digital/juncture] Editor window won't launch correctly (Issue #34)





Ann,



I’m working on a fix, or at least an interim solution. I’m hoping to have something in place in the next day or two. I’ll post an update when it’s ready.



Also, I’d be interested in hearing more about how this is being used in class if you’d care to share some details when you have a chance.



Ron

**Comment by annhanlon** [comment]
Sorry, that got starred out so I didn't get the alternate email,

Ann


Ann Hanlon, M.L.I.S., M.A.
Head, Digital Collections and Initiatives and DH Services
University of Wisconsin-Milwaukee Libraries
pronouns-in-use: she/her/hers
________________________________

**Comment by rsnyder** [comment]
I’m sure this is to protect us from ourselves...  Try using the “Contact Us” link found in the main menu (located on the right side of the header) on the https://v3.juncture-digital.org site.

Ron

**Comment by rsnyder** [comment]
This issue is resolved.  The editor should now be loading.  The code highlighting is temporarily disabled however.  That will be addressed in a subsequent update.
