### ISSUE TITLE
Can't Annotate Text!

### ISSUE THREAD

**Issue by Isabel-Vue-UWM** [juncture-digital/juncture#36]
I followed the directions from the "How to Guides," but they're not appearing whenever I save and share. Plus, the video isn't there to complete the following steps in the "How to Guides."

**Comment by Isabel-Vue-UWM** [comment]
<img width="625" alt="Screenshot 2024-10-04 at 6 50 01 PM" src="https://github.com/user-attachments/assets/51d67197-0798-444b-945b-ae026ebd4c86">
<img width="643" alt="Screenshot 2024-10-04 at 6 50 07 PM" src="https://github.com/user-attachments/assets/2b05fdf9-de23-420a-a160-1fc6c48355d9">

**Comment by rsnyder** [comment]
Would you be able to add a link to your essay?  That would be helpful in diagnosing the issue.  A quick check of the Juncture annotation feature just now shows it to be working.

**Comment by Isabel-Vue-UWM** [comment]
https://www.juncture-digital.org/Isabel-Vue-UWM/essays

**Comment by rsnyder** [comment]
Thanks for providing this link.  It looks like you've uncovered a bug with annotating essays located at the root of a Github repository.  I'll need to look into this more and make a correction to the annotation software.  In the meantime, there's an easy work around - just put the essay into a subfolder in your repository.  For instance, something like `frederick-stuart-church`.  This can be done easily in the Github web interface by navigating to the essay [README.md](https://github.com/Isabel-Vue-UWM/essays/blob/main/README.md) file, selecting the edit button (pencil icon) from the toolbar, and replacing `README.md` with `frederick-stuart-church/README.md` in the file name input box.  This will create a `frederick-stuart-church` folder for the essay.  After that's done the image annotation should work.  If you're using the Juncture editor you'll need to update the editor to reference the new location.  Please let me know if you run into any issues with this workaround.

**Comment by Isabel-Vue-UWM** [comment]
Thank you, rsnyder. I tried your method of creating a new folder and it sort of worked! Although I can only see my annotation whenever I share my essay, and that I have to edit it a certain way or else it disappears on me again, I think it's enough for me to handle. I'll make sure to keep an eye out for any changes or update on Juncture. Thanks, again. 

How I add annotation (for whomever has this same issue like me)

1. Click Toggle Preview
2. Hover over a picture in Preview Mode
3. Click the Edit icon (Chat box icon)
4. Press shift to create a box, then type whatever you like.
5. Once your done, go back to Toggle Preview 
6. Click the share button to see your annotation

**Comment by rsnyder** [comment]
Glad the workaround enabled you to move forward.  And thank you for the additional info on the annotation editing quirkiness.  I've been working on an updated version of the editor and this will be helpful input.

Your essay looks great, BTW.  Nicely done!
